apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-web-agent
  namespace: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: web-agent
  replicas: 1
  template:
    metadata:
      labels:
        app: web-agent
    spec:
      serviceAccountName: ignite-cluster
      containers:
        - name: web-agent
          image: apacheignite/web-agent:mytag3
          imagePullPolicy: Always
          env:
            - name: DRIVER_FOLDER
              value: "./jdbc-drivers"
            - name: NODE_URI
              value: "http://ignite-service.ignite.svc.cluster.local:8080"
            - name: SERVER_URI
              value: "http://frontend.web-console.svc.cluster.local"
            - name: TOKENS
              value: ""
            - name: NODE_LOGIN
              value: web-agent
            - name: NODE_PASSWORD
              value: password
          